services:
    dev-db:
        image: postgres
        container_name: ecommerce_dev_db
        restart: always
        ports:
            - 5433:5432
        environment:
            POSTGRES_PASSWORD: kareem
            POSTGRES_DB: ecommerce

    test-db:
        image: postgres
        container_name: ecommerce_test_db
        restart: always
        ports:
            - 5434:5432
        environment:
            POSTGRES_PASSWORD: kareem
            POSTGRES_DB: ecommerce
